# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
cluster:
  name: dynamo-log-collector

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway.$MONITORING_NAMESPACE.svc.cluster.local/loki/api/v1/push

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labels:
    app_kubernetes_io_name: app.kubernetes.io/name
    nvidia_com_dynamo_component_type: nvidia.com/dynamo-component-type
    nvidia_com_dynamo_graph_deployment_name: nvidia.com/dynamo-graph-deployment-name
  labelsToKeep:
    - "app_kubernetes_io_name"
    - "container"
    - "instance"
    - "job"
    - "level"
    - "namespace"
    - "service_name"
    - "service_namespace"
    - "deployment_environment"
    - "deployment_environment_name"
    - "nvidia_com_dynamo_component_type"
    - "nvidia_com_dynamo_graph_deployment_name"
  structuredMetadata:
    pod: pod  # Set structured metadata "pod" from label "pod"
  namespaces:
    - $DYNAMO_NAMESPACE

# Collectors
alloy-singleton:
  enabled: false

alloy-metrics:
  enabled: false

alloy-logs:
  enabled: true
  alloy:
    mounts:
      varlog: false
      dockercontainers: false
    clustering:
      enabled: true

alloy-profiles:
  enabled: false

alloy-receiver:
  enabled: false