# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: sglang-agg
spec:
  envs:
  - name: DYN_LOGGING_JSONL
    value: "1"
  services:
    Frontend:
      dynamoNamespace: sglang-agg
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: my-registry/sglang-runtime:my-tag
    SGLangDecodeWorker:
      envFromSecret: hf-token-secret
      dynamoNamespace: sglang-agg
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: my-registry/sglang-runtime:my-tag
          workingDir: /workspace/components/backends/sglang
          command:
          - /bin/sh
          - -c
          args:
          - >-
            python3 -m dynamo.sglang
            --model-path Qwen/Qwen3-0.6B
            --served-model-name Qwen/Qwen3-0.6B
            --page-size 16
            --tp 1
            --trust-remote-code
            --skip-tokenizer-init